# Generated by Django 4.2.6 on 2023-10-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('emp_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='_emp_id')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='_email')),
                ('f_name', models.CharField(max_length=30, verbose_name='_f_name')),
                ('l_name', models.CharField(max_length=30, verbose_name='_l_name')),
                ('cell_no', models.CharField(max_length=13, verbose_name='_cell_no')),
                ('designation', models.CharField(max_length=15, verbose_name='_designation')),
                ('gender', models.CharField(max_length=15, verbose_name='_gender')),
                ('password', models.CharField(max_length=10, verbose_name='_password')),
                ('birth_date', models.DateTimeField(default='2000-7-22')),
                ('nfc_num', models.BigIntegerField(default=-1, verbose_name='_nfc_num')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is_staff')),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group', verbose_name='Groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_user_permissions', to='auth.permission', verbose_name='User permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
