# Generated by Django 4.2.6 on 2023-10-26 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_dailyhours'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dailyhours',
            new_name='daily_hours',
        ),
    ]
