# Generated by Django 4.2.6 on 2023-10-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employees_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_hours',
            name='hours',
            field=models.DateTimeField(),
        ),
    ]
